apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nginx
 spec:
  tls:
    - hosts:
      - example.com
      secretName: example-com-tls
  rules:
  - host: example.com
    http:
      paths:
      - backend:
          serviceName: nginx
          servicePort: 80
