apiVersion: apps/v1
kind: Ingress
metadata:
  name: nginx
spec:
  tls:
    - hosts:
      - 192.168.99.100
      secretName: nginx-certs-keys
  rules:
  - host: 192.168.99.100
    http:
      paths:
      - backend:
          serviceName: nginx
          servicePort: 80
