apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-deploy
  labels:
    app: jenkins
spec:
  replicas: 6
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
      - name: nginx
        image: arvindgpt88/gupta123:jenkins
        ports:
        - containerPort: 80  
