apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-testimage
  labels:
    app: jenkins
spec:
  replicas: 6
  selector:
    matchLabels:
      app: testimage
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
      - name: testimage
        image: nginx
        ports:
        - containerPort: 80  
