apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-java
  labels:
    app: java
spec:
  replicas: 6
  selector:
    matchLabels:
      app: java
  template:
    metadata:
      labels:
        app: java
    spec:
      containers:
      - name: java
        image: arvindgpt88/gupta123:java
        ports:
        - containerPort: 80  
