apiVersion: v1
kind: Service
metadata:
  name: nginxhttpsvc
  labels:
    app: nginxhttps
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    name: http
  - port: 443
    protocol: TCP
    name: https
  selector:
    app: nginxhttps
---    
apiVersion: v1
kind: ReplicationController
metadata:
  name: nginxhttpsdeploy
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: nginxhttps
    spec:   
     containers:
      - name: nginxhttpsdeploy
        image: nginx
        ports:
        - containerPort: 443
        - containerPort: 80
---
apiVersion: v1
kind: Ingress
metadata:
 name: nginxhttpsvc
spec:
 tls:
   - secretName: nginx-certs-keys  
 rules:
   - http:
        paths:
          - backend:
               serviceName: nginx
               servicePort: 80
