apiVersion: v1
kind: Service
metadata:
  name: nginxhttpsvc
  labels:
    app: nginxhttps
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    name: http
  - port: 443
    protocol: TCP
    name: https
  selector:
    app: nginxhttps
---    
apiVersion: v1
kind: ReplicationController
metadata:
  name: nginxhttpsdeploy
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: nginxhttps
    spec:   
     volumes:
      - name: secret-volume
        secret:
           secretName: nginx-certs-keys
      - name: configmap-volume
        configMap:
           name: nginxconfigmap
     containers:
      - name: nginxhttpsdeploy
        image: nginx
        ports:
        - containerPort: 443
        - containerPort: 80
        volumeMounts:
        - mountPath: C:\Kube\nginx.crt C:\Kube\nginx.key
          name: secret-volume
        - mountPath: C:\Kube\default.conf.txt
          name: configmap-volume
