apiVersion: v1
kind: Service
metadata:
  name: nginxsvc
  labels:
    app: nginxhttps
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    name: http
  - port: 443
    protocol: TCP
    name: https
  selector:
    app: nginxhttps
---    
apiVersion: apps/v1
kind: ReplicationController
metadata:
  name: deploy-nginxhttps
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: nginxhttps
    spec:
     volumes:
      - name: secret-volume
        secret:
           secretName: nginx-certs-keys
     containers:
      - name: deploy-nginxhttps
        image: nginx
        ports:
        - containerPort: 443
        - containerPort: 80
